/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeesIndexRouteImport } from './routes/employees/index'
import { Route as EmployeesEmployeeIdAttendanceRouteImport } from './routes/employees/$employeeId.attendance'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesIndexRoute = EmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesEmployeeIdAttendanceRoute =
  EmployeesEmployeeIdAttendanceRouteImport.update({
    id: '/employees/$employeeId/attendance',
    path: '/employees/$employeeId/attendance',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/employees/': typeof EmployeesIndexRoute
  '/employees/$employeeId/attendance': typeof EmployeesEmployeeIdAttendanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/employees': typeof EmployeesIndexRoute
  '/employees/$employeeId/attendance': typeof EmployeesEmployeeIdAttendanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/employees/': typeof EmployeesIndexRoute
  '/employees/$employeeId/attendance': typeof EmployeesEmployeeIdAttendanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/employees/' | '/employees/$employeeId/attendance'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/employees' | '/employees/$employeeId/attendance'
  id: '__root__' | '/' | '/employees/' | '/employees/$employeeId/attendance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmployeesIndexRoute: typeof EmployeesIndexRoute
  EmployeesEmployeeIdAttendanceRoute: typeof EmployeesEmployeeIdAttendanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/': {
      id: '/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof EmployeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/$employeeId/attendance': {
      id: '/employees/$employeeId/attendance'
      path: '/employees/$employeeId/attendance'
      fullPath: '/employees/$employeeId/attendance'
      preLoaderRoute: typeof EmployeesEmployeeIdAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmployeesIndexRoute: EmployeesIndexRoute,
  EmployeesEmployeeIdAttendanceRoute: EmployeesEmployeeIdAttendanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
